db-move: moved krb5 from [testing] to [core] (i686, x86_64)
git-svn-id: file:///srv/repos/svn-packages/svn@219603 eb2447ed-0c53-47e4-bac8-5bc4a241df78

diff --git a/repos/core-x86_64/PKGBUILD b/repos/core-x86_64/PKGBUILD
--- a/repos/core-x86_64/PKGBUILD
+++ b/repos/core-x86_64/PKGBUILD
@@ -3,7 +3,7 @@
 
 pkgname=krb5
 pkgver=1.12.1
-pkgrel=1
+pkgrel=2
 pkgdesc="The Kerberos network authentication system"
 arch=('i686' 'x86_64')
 url="http://web.mit.edu/kerberos/"
@@ -12,34 +12,35 @@ depends=('e2fsprogs' 'libldap' 'keyutils')
 makedepends=('perl')
 backup=('etc/krb5.conf' 'var/lib/krb5kdc/kdc.conf')
 options=('!emptydirs')
-source=(http://web.mit.edu/kerberos/dist/${pkgname}/${pkgver%.*}/${pkgname}-${pkgver}-signed.tar
+source=(http://web.mit.edu/kerberos/dist/krb5/${pkgver%.*}/${pkgname}-${pkgver}-signed.tar
         krb5-config_LDFLAGS.patch
         krb5-kadmind.service
         krb5-kdc.service
         krb5-kpropd.service
         krb5-kpropd@.service
-        krb5-kpropd.socket)
+        krb5-kpropd.socket
+	krb5-81c332e29f10887c6b9deb065f81ba259f4c7e03.patch)
 sha1sums=('d59e8dc0fc9e1890e109cd033756539984e3d3fe'
-          '09e478cddfb9d46d2981dd25ef96b8c3fd91e1aa'
+          'f125824ed37f31e6fd2fdb6a437be8ff1c3700ab'
           '59bbc7e686cbb4bcefddf0f134d928d7bd5e7722'
           '2ef2476a8673b3b702e829d8f451c839c2273b02'
           '74d66aefd291f22dd80799f0437cc03d83083ed5'
           '6787c6ce2783b3f980c423e2dd4abf5236af670b'
-          'f3677d30dbbd7106c581379c2c6ebb1bf7738912')
+          'f3677d30dbbd7106c581379c2c6ebb1bf7738912'
+          '8273976824137df1d42a4f9c7bafdfbd92f27d0a')
 
 prepare() {
-  tar -xf ${pkgname}-${pkgver}.tar.gz
   # the signature and source are bundled together, so signature check needs to be done here
-  local statusfile=$(mktemp)
-  (( SKIPPGPCHECK )) || gpg --quiet --batch --status-file "$statusfile" --verify krb5-${pkgver}.tar.gz.asc krb5-${pkgver}.tar.gz 2> /dev/null
-  rm "$statusfile"
+  _check_pgpsig
 
-  cd ${pkgname}-${pkgver}/src
+  tar -xf ${pkgname}-${pkgver}.tar.gz
+  cd ${pkgname}-${pkgver}
   # cf https://bugs.gentoo.org/show_bug.cgi?id=448778
-  (cd build-tools;  patch -Np2 -i "${srcdir}"/krb5-config_LDFLAGS.patch; cd ..)
+  patch -p1 -i "${srcdir}"/krb5-config_LDFLAGS.patch
+  patch -p1 -i "${srcdir}"/krb5-81c332e29f10887c6b9deb065f81ba259f4c7e03.patch
 
    # FS#25384
-   sed -i "/KRB5ROOT=/s/\/local//" util/ac_check_krb5.m4
+   sed -i "/KRB5ROOT=/s/\/local//" src/util/ac_check_krb5.m4
 }
 
 build() {
@@ -85,4 +86,57 @@ package() {
    install -dm 755 "${pkgdir}"/usr/lib/systemd/system
    install -m 644 ../../krb5-{kadmind.service,kdc.service,kpropd.service,kpropd@.service,kpropd.socket} \
       "${pkgdir}"/usr/lib/systemd/system
+}
+
+_check_pgpsig() {
+  (( SKIPPGPCHECK )) && return 0
+
+  msg "$(gettext "Verifying source file signatures with %s...")" "gpg"
+
+  local file=${pkgname}-${pkgver}.tar.gz.asc
+  local sourcefile=${file%.*}
+  local pubkey
+  local warning=0
+  local errors=0
+  local statusfile=$(mktemp)
+
+  printf "    %s ... " "${file%.*}" >&2
+
+  if ! gpg --quiet --batch --status-file "$statusfile" --verify "$file" "$sourcefile" 2> /dev/null; then
+    printf "FAILED" >&2
+    if ! pubkey=$(awk '/NO_PUBKEY/ { print $3; exit 1; }' "$statusfile"); then
+      printf " (unknown public key $pubkey)" >&2
+      warnings=1
+    else
+      errors=1
+    fi
+    printf '\n' >&2
+  else
+    if grep -q "REVKEYSIG" "$statusfile"; then
+      printf "FAILED (the key has been revoked.)" >&2
+      errors=1
+    else
+      printf "Passed" >&2
+      if grep -q "EXPSIG" "$statusfile"; then
+        printf " (WARNING: the signature has expired.)" >&2
+        warnings=1
+      elif grep -q "EXPKEYSIG" "$statusfile"; then
+        printf " (WARNING: the key has expired.)" >&2
+        warnings=1
+      fi
+    fi
+    printf '\n' >&2
+  fi
+  
+  rm -f "$statusfile"
+
+  if (( errors )); then
+    error "One or more PGP signatures could not be verified!"
+    exit 1
+  fi
+
+  if (( warnings )); then
+    warning "Warnings have occurred while verifying the signatures."
+    plain "Please make sure you really trust them."
+  fi
 }
