Remove usage of error() makepkg subroutine
git-svn-id: file:///srv/repos/svn-packages/svn@382641 eb2447ed-0c53-47e4-bac8-5bc4a241df78

diff --git a/geoip-database/trunk/PKGBUILD b/geoip-database/trunk/PKGBUILD
--- a/geoip-database/trunk/PKGBUILD
+++ b/geoip-database/trunk/PKGBUILD
@@ -30,32 +30,32 @@ check() {
   cd "$srcdir"
 
   if [[ $(geoiplookup -f GeoIP.dat 8.8.8.8) != *'US, United States' ]]; then
-    error 'Unable to resolve IPv4 address to country.'
+    echo >&2 'Unable to resolve IPv4 address to country.'
     return 1
   fi
 
   if [[ $(geoiplookup6 -f GeoIPv6.dat 2001:4860:4860::8888) != *'US, United States' ]]; then
-    error 'Unable to resolve IPv6 address to country.'
+    echo >&2 'Unable to resolve IPv6 address to country.'
     return 1
   fi
 
   if [[ $(geoiplookup -f GeoIPCity.dat 8.8.8.8) != *'US, 00, N/A, N/A'* ]]; then
-    error 'Unable to resolve IPv4 address to city.'
+    echo >&2 'Unable to resolve IPv4 address to city.'
     return 1
   fi
 
   if [[ $(geoiplookup6 -f GeoIPCityv6.dat 2001:4860:4860::8888) != *'US, 00, N/A, N/A'* ]]; then
-    error 'Unable to resolve IPv6 address to city.'
+    echo >&2 'Unable to resolve IPv6 address to city.'
     return 1
   fi
 
   if [[ $(geoiplookup -f GeoIPASNum.dat 8.8.8.8) != *'AS15169 GOOGLE' ]]; then
-    error 'Unable to resolve IPv4 address to ASN.'
+    echo >&2 'Unable to resolve IPv4 address to ASN.'
     return 1
   fi
 
   if [[ $(geoiplookup6 -f GeoIPASNumv6.dat 2001:4860:4860::8888) != *'AS15169 GOOGLE' ]]; then
-    error 'Unable to resolve IPv6 address to ASN.'
+    echo >&2 'Unable to resolve IPv6 address to ASN.'
     return 1
   fi
 }
