gptfdisk is not installed by default, this causes cryptic syslinux installation errors that confuses many users. Make the error message more obvious.
git-svn-id: file:///srv/repos/svn-packages/svn@228088 eb2447ed-0c53-47e4-bac8-5bc4a241df78

diff --git a/syslinux/trunk/syslinux-install_update b/syslinux/trunk/syslinux-install_update
--- a/syslinux/trunk/syslinux-install_update
+++ b/syslinux/trunk/syslinux-install_update
@@ -246,6 +246,11 @@ set_active() {
                 exit 3
             fi
         elif [[ "$ptb" = GPT ]]; then
+            if [[ ! -e /usr/bin/sgdisk ]]; then
+                echo "FAILED to set attribute Legacy BIOS Bootable. sgdisk is not found - please install 'gptfdisk' package."
+                exit 3
+            fi
+
             if sgdisk "$disk" --attributes="$partnum":set:2 &>/dev/null; then
                 echo "Attribute Legacy Bios Bootable Set - $part"
             else
