Make error message cleaner for non-partitioned disks
syslinux requires partition table is we want to install MBR or active bit.
Make the error message cleaner.

Inspired by https://bbs.archlinux.org/viewtopic.php?id=223038



git-svn-id: file:///srv/repos/svn-packages/svn@288769 eb2447ed-0c53-47e4-bac8-5bc4a241df78

diff --git a/syslinux/trunk/syslinux-install_update b/syslinux/trunk/syslinux-install_update
--- a/syslinux/trunk/syslinux-install_update
+++ b/syslinux/trunk/syslinux-install_update
@@ -233,7 +233,7 @@ set_active() {
     # If any bootdev is a block device without partitions bail
     # we want to set the boot flag on partitioned disk
     for dev in "${!bootdevs[@]}"; do
-        dev_is_part $dev || { echo "$dev - is a block device. Aborting set_active!"; return 1; }
+        dev_is_part $dev || { echo "$dev does not contain partition table. Aborting set_active!"; return 1; }
     done
 
     # Clear BIOS Bootable Legacy Attribute for GPT drives
@@ -281,7 +281,7 @@ install_mbr() {
     # If any bootdev is a block device without partitions bail
     # we want to install the mbr to a partitioned disk
     for dev in "${!bootdevs[@]}"; do
-        dev_is_part "$dev" || { echo "$dev - is a block device. Aborting MBR install"; return 1; }
+        dev_is_part "$dev" || { echo "$dev does not contain partition table. Aborting MBR install."; return 1; }
     done
 
     for part in "${!bootdevs[@]}"; do
