upgpkg: texlive-bin 2011.2-1
Texlive update.

git-svn-id: file:///srv/repos/svn-packages/svn@144304 eb2447ed-0c53-47e4-bac8-5bc4a241df78

diff --git a/trunk/archlinux-build.patch b/trunk/archlinux-build.patch
--- a/trunk/archlinux-build.patch
+++ b/trunk/archlinux-build.patch
@@ -1,21 +1,19 @@
-diff -ur source.old/texk/am/script_links.am source/texk/am/script_links.am
---- source.old/texk/am/script_links.am	2011-05-02 13:54:33.000000000 +0200
-+++ source/texk/am/script_links.am	2011-06-05 11:22:53.118216353 +0200
-@@ -51,8 +51,8 @@
- # We support both multiplatform and non-multiplatform builds.
+diff -aur source/texk/am/script_links.am source.new/texk/am/script_links.am
+--- source/texk/am/script_links.am	2011-09-29 14:17:38.000000000 +0200
++++ source.new/texk/am/script_links.am	2011-12-04 13:14:35.480368959 +0100
+@@ -52,7 +52,7 @@
+ 
+ # We support native builds, multiplatform or not, as well as distro builds.
  install-links:
- 	case "$(bindir)" in \
--	  */bin) $(MAKE) $(AM_MAKEFLAGS) REL=.. TYPE=$(TYPE) EXT=$(EXT) make-links;; \
--	  */bin/*) $(MAKE) $(AM_MAKEFLAGS) REL=../.. TYPE=$(TYPE) EXT=$(EXT) make-links;; \
-+	  */bin) $(MAKE) $(AM_MAKEFLAGS) REL=$(datadir) TYPE=$(TYPE) EXT=$(EXT) make-links;; \
-+	  */bin/*) $(MAKE) $(AM_MAKEFLAGS) REL=$(datadir) TYPE=$(TYPE) EXT=$(EXT) make-links;; \
- 	  *) echo "strange directory '$(bindir)' for linked $(TYPE) scripts" >&2; \
- 	     exit 1;; \
- 	esac
-diff -ur source.old/texk/tetex/Makefile.am source/texk/tetex/Makefile.am
---- source.old/texk/tetex/Makefile.am	2011-05-31 11:47:04.000000000 +0200
-+++ source/texk/tetex/Makefile.am	2011-06-05 10:28:40.287025375 +0200
-@@ -35,7 +35,7 @@
+-	@REL=`$(SHELL) $(srcdir)/../../build-aux/relpath '$(DESTDIR)' '$(bindir)' '$(prefix)'`; \
++	@REL=$(datadir); \
+ 	if test -z "$$REL"; then \
+ 	  echo 'unable to compute relative path for linked $(TYPE) scripts' >&2; \
+ 	  exit 1; \
+diff -aur source/texk/tetex/Makefile.am source.new/texk/tetex/Makefile.am
+--- source/texk/tetex/Makefile.am	2011-09-29 14:14:07.000000000 +0200
++++ source.new/texk/tetex/Makefile.am	2011-12-04 13:13:32.089463768 +0100
+@@ -37,7 +37,7 @@
  
  include $(srcdir)/../am/script_links.am
  
@@ -24,17 +22,15 @@ diff -ur source.old/texk/tetex/Makefile.am source/texk/tetex/Makefile.am
  dist_texmf_SCRIPTS = $(perl_scripts:=.pl) $(shell_scripts:=.sh)
  
  if !WIN32
-diff -ur source.old/texk/texlive/linked_scripts/Makefile.am source/texk/texlive/linked_scripts/Makefile.am
---- source.old/texk/texlive/linked_scripts/Makefile.am	2011-05-31 11:47:04.000000000 +0200
-+++ source/texk/texlive/linked_scripts/Makefile.am	2011-06-05 09:41:50.997250443 +0200
-@@ -165,8 +165,8 @@
- 	done
- else !WIN32
- 	case "$(bindir)" in \
--	  */bin) $(MAKE) $(AM_MAKEFLAGS) REL=.. install-links;; \
--	  */bin/*) $(MAKE) $(AM_MAKEFLAGS) REL=../.. install-links;; \
-+	  */bin) $(MAKE) $(AM_MAKEFLAGS) REL=$(datadir) install-links;; \
-+	  */bin/*) $(MAKE) $(AM_MAKEFLAGS) REL=$(datadir) install-links;; \
- 	  *) echo "strange directory '$(bindir)' for linked scripts" >&2; \
- 	     exit 1;; \
- 	esac
+diff -aur source/texk/texlive/linked_scripts/Makefile.am source.new/texk/texlive/linked_scripts/Makefile.am
+--- source/texk/texlive/linked_scripts/Makefile.am	2011-12-03 17:22:19.000000000 +0100
++++ source.new/texk/texlive/linked_scripts/Makefile.am	2011-12-04 13:14:20.550940820 +0100
+@@ -177,7 +177,7 @@
+ ## Name the link as the basename, removing any extension,
+ ## except for listings-ext.sh, which is documented as that name.
+ ## Downcase for the sake of TeXcount.pl -> texcount.
+-	@REL=`$(relpath) '$(DESTDIR)' '$(bindir)' '$(prefix)'`; \
++	@REL=$(datadir); \
+ 	if test -z "$$REL"; then \
+ 	  echo 'unable to compute relative path for linked scripts' >&2; \
+ 	  exit 1; \
