1.14.0-1
git-svn-id: file:///srv/repos/svn-packages/svn@454464 eb2447ed-0c53-47e4-bac8-5bc4a241df78

diff --git a/trunk/fusermount3.diff b/trunk/fusermount3.diff
--- a/trunk/fusermount3.diff
+++ b/trunk/fusermount3.diff
@@ -1,8 +1,8 @@
 diff --git i/common/flatpak-dir.c w/common/flatpak-dir.c
-index 3f8f2567..aeb75c9b 100644
+index ca64902c..22302406 100644
 --- i/common/flatpak-dir.c
 +++ w/common/flatpak-dir.c
-@@ -2020,7 +2020,7 @@ flatpak_dir_revokefs_fuse_unmount (OstreeRepo **repo,
+@@ -2109,7 +2109,7 @@ flatpak_dir_revokefs_fuse_unmount (OstreeRepo **repo,
  
    fusermount = g_subprocess_new (G_SUBPROCESS_FLAGS_NONE,
                                   error,
@@ -12,10 +12,10 @@ index 3f8f2567..aeb75c9b 100644
    if (g_subprocess_wait_check (fusermount, NULL, error))
      {
 diff --git i/tests/can-use-fuse.c w/tests/can-use-fuse.c
-index 25f3936e..83517c89 100644
+index fb6e2000..759f0d84 100644
 --- i/tests/can-use-fuse.c
 +++ w/tests/can-use-fuse.c
-@@ -41,23 +41,23 @@ check_fuse (void)
+@@ -53,23 +53,23 @@ check_fuse (void)
        return FALSE;
      }
  
@@ -43,10 +43,10 @@ index 25f3936e..83517c89 100644
      }
  
 diff --git i/tests/libtest.sh w/tests/libtest.sh
-index 4a9fd481..5921dda5 100644
+index 36d39ac4..e78d94ca 100644
 --- i/tests/libtest.sh
 +++ w/tests/libtest.sh
-@@ -536,7 +536,7 @@ skip_one_without_bwrap () {
+@@ -542,7 +542,7 @@ skip_one_without_bwrap () {
  }
  
  skip_without_fuse () {
@@ -55,12 +55,12 @@ index 4a9fd481..5921dda5 100644
  
      capsh --print | grep -q 'Bounding set.*[^a-z]cap_sys_admin' || \
          skip "No cap_sys_admin in bounding set, can't use FUSE"
-@@ -595,7 +595,7 @@ commit_to_path () {
+@@ -608,7 +608,7 @@ commit_to_path () {
  cleanup () {
      /bin/kill -9 $DBUS_SESSION_BUS_PID
-     gpg-connect-agent --homedir "${FL_GPG_HOMEDIR}" killagent /bye || true
--    fusermount -u $XDG_RUNTIME_DIR/doc || :
-+    fusermount3 -u $XDG_RUNTIME_DIR/doc || :
+     gpg-connect-agent --homedir "${FL_GPG_HOMEDIR}" killagent /bye >&2 || true
+-    fusermount -u $XDG_RUNTIME_DIR/doc >&2 || :
++    fusermount3 -u $XDG_RUNTIME_DIR/doc >&2 || :
      kill $(jobs -p) &> /dev/null || true
      if test -n "${TEST_SKIP_CLEANUP:-}"; then
-         echo "Skipping cleanup of ${TEST_DATA_DIR}"
+         echo "# Skipping cleanup of ${TEST_DATA_DIR}"
