upgpkg: liferea 1.6.6b-1 Upstream update, Updated libnotify patch, Cleaned up depends
git-svn-id: file:///srv/repos/svn-packages/svn@128336 eb2447ed-0c53-47e4-bac8-5bc4a241df78

diff --git a/trunk/libnotify-0.7.patch b/trunk/libnotify-0.7.patch
--- a/trunk/libnotify-0.7.patch
+++ b/trunk/libnotify-0.7.patch
@@ -19,3 +19,50 @@ diff -u -Nr liferea-1.6.5/src/notification/libnotify.c liferea-1.6.5-libnotify/s
  	g_free(labelSummary_p);
  
  	notify_notification_set_icon_from_pixbuf (n, node_get_icon (node));
+diff -Naur liferea-1.6.6b/configure liferea-1.6.6b-new/configure
+--- liferea-1.6.6b/configure	2011-06-22 11:16:46.000000000 -0400
++++ liferea-1.6.6b-new/configure	2011-06-22 19:41:18.000000000 -0400
+@@ -12567,12 +12567,12 @@
+     pkg_cv_LIBNOTIFY_CFLAGS="$LIBNOTIFY_CFLAGS"
+  elif test -n "$PKG_CONFIG"; then
+     if test -n "$PKG_CONFIG" && \
+-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libnotify >= 0.3.2, libnotify <= 0.5\""; } >&5
+-  ($PKG_CONFIG --exists --print-errors "libnotify >= 0.3.2, libnotify <= 0.5") 2>&5
++    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libnotify >= 0.3.2, libnotify <= 0.8\""; } >&5
++  ($PKG_CONFIG --exists --print-errors "libnotify >= 0.3.2, libnotify <= 0.8") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   test $ac_status = 0; }; then
+-  pkg_cv_LIBNOTIFY_CFLAGS=`$PKG_CONFIG --cflags "libnotify >= 0.3.2, libnotify <= 0.5" 2>/dev/null`
++  pkg_cv_LIBNOTIFY_CFLAGS=`$PKG_CONFIG --cflags "libnotify >= 0.3.2, libnotify <= 0.8" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -12583,12 +12583,12 @@
+     pkg_cv_LIBNOTIFY_LIBS="$LIBNOTIFY_LIBS"
+  elif test -n "$PKG_CONFIG"; then
+     if test -n "$PKG_CONFIG" && \
+-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libnotify >= 0.3.2, libnotify <= 0.5\""; } >&5
+-  ($PKG_CONFIG --exists --print-errors "libnotify >= 0.3.2, libnotify <= 0.5") 2>&5
++    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libnotify >= 0.3.2, libnotify <= 0.8\""; } >&5
++  ($PKG_CONFIG --exists --print-errors "libnotify >= 0.3.2, libnotify <= 0.8") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   test $ac_status = 0; }; then
+-  pkg_cv_LIBNOTIFY_LIBS=`$PKG_CONFIG --libs "libnotify >= 0.3.2, libnotify <= 0.5" 2>/dev/null`
++  pkg_cv_LIBNOTIFY_LIBS=`$PKG_CONFIG --libs "libnotify >= 0.3.2, libnotify <= 0.8" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -12608,9 +12608,9 @@
+         _pkg_short_errors_supported=no
+ fi
+         if test $_pkg_short_errors_supported = yes; then
+-	        LIBNOTIFY_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "libnotify >= 0.3.2, libnotify <= 0.5" 2>&1`
++	        LIBNOTIFY_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "libnotify >= 0.3.2, libnotify <= 0.8" 2>&1`
+         else
+-	        LIBNOTIFY_PKG_ERRORS=`$PKG_CONFIG --print-errors "libnotify >= 0.3.2, libnotify <= 0.5" 2>&1`
++	        LIBNOTIFY_PKG_ERRORS=`$PKG_CONFIG --print-errors "libnotify >= 0.3.2, libnotify <= 0.8" 2>&1`
+         fi
+ 	# Put the nasty error message in config.log where it belongs
+ 	echo "$LIBNOTIFY_PKG_ERRORS" >&5
