update to TeXLive 2009 (testing); clean old patches
git-svn-id: file:///srv/repos/svn-packages/svn@47170 eb2447ed-0c53-47e4-bac8-5bc4a241df78

diff --git a/trunk/PKGBUILD b/trunk/PKGBUILD
--- a/trunk/PKGBUILD
+++ b/trunk/PKGBUILD
@@ -1,24 +1,19 @@
-# $Id$
 # Maintainer: francois at archlinux dot org
 
 pkgname=texlive-bin
-pkgver=2008
-pkgrel=5
+pkgver=2009
+pkgrel=pre5
 pkgdesc="TeX Live binaries"
 license=('GPL')
 arch=('i686' 'x86_64')
-depends=('readline>=6.0.00' 'gcc-libs' 't1lib' 'gd' 'libsigsegv')
+depends=('gcc-libs' 't1lib' 'gd' 'libsigsegv')
 optdepends=('psutils' 't1utils' 'perl')
-makedepends=('clisp' 'ffcall' 'lzma-utils')
-conflicts=('texlive-omega')
+makedepends=('clisp' 'ffcall')
+##conflicts=('asymptote')
+##provides=('asymptote=1.80')
 options=('!makeflags' '!libtool')
 url='http://tug.org/texlive/'
-source=('texmf.cnf' 'ftp://tug.org/texlive/historic/2008/texlive-20080816-source.tar.lzma' \
-	'ftp://ftp.archlinux.org/other/texlive/texlive-bin-2008-texmf.tar.lzma' \
-        'texlive-gcc44.patch' 'texlive-glibc-210.patch' 'texlive-lua.patch')
-md5sums=('351a6136e4faafe7fba123a07aef7787' '554287c3e458da776edd684506048d45'\
-         'bac8aee05595fb80fcae8e864ba063f6' '51a7d90c3dda9bde3d11f443775fa7f4'\
-         'fb839a23dc81889c0796fe6ea5817b4d' 'bf65fb9d3d644ae7a452d7a388d08f37')
+source=('texmf.cnf' 'source-20090723.tar.xz' 'texmf-20090723.tar.xz')
 backup=(usr/share/texmf/web2c/texmf.cnf \
 	usr/share/texmf-config/web2c/mktex.cnf \
 	usr/share/texmf-config/web2c/updmap.cfg \
@@ -30,102 +25,114 @@ backup=(usr/share/texmf/web2c/texmf.cnf \
 	usr/share/texmf-config/dvipdfm/dvipdfmx.cfg \
 	usr/share/texmf-config/dvipdfm/config/config \
 	usr/share/texmf-config/xdvi/XDvi)
+md5sums=('351a6136e4faafe7fba123a07aef7787'
+         '6f39667d832949017c1273dcd4b9606d'
+         'a84922fc1947a5c581c10eb4b75358f3')
 build() {
-   cd $srcdir
    if [ "${CARCH}" = "x86_64" ]; then
      export CFLAGS="${CFLAGS} -fPIC"
      export CXXFLAGS="${CXXFLAGS} -fPIC"
    fi
-   lzma --force -dc texlive-bin-2008-texmf.tar.lzma | tar xf - || return 1
+
+   cd $srcdir
+
    install -m755 -d $pkgdir/usr/share || return 1
-   find texmf -type d -exec install -d -m755 $pkgdir/usr/share/'{}' \; || return 1
-   find texmf -type f -exec install -m644 '{}' $pkgdir/usr/share/'{}' \; || return 1
-   lzma --force -dc texlive-20080816-source.tar.lzma | tar xf - || return 1
-   patch -p0 < texlive-gcc44.patch || return 1
-   patch -p0 < texlive-glibc-210.patch || return 1
-   patch -p0 < texlive-lua.patch || return 1
-   cd texlive-20080816-source || return 1
-   # This trick is for avoiding exiting when latex is not available, 
-   # since we do not build the xindy documentation anyway:
-   sed -i~ 's|latex="no"|latex="yes"|' utils/xindy/configure || return 1
+   cp -r texmf $pkgdir/usr/share/ || return 1
+   ## TODO  
+   ## same problem with latest german patterns!
+   # currently latvian hyphenation is missing:
+   # FIXME reenable when texlive-core 2009 is available
+   ## sed -i 's|^\addlanguage{latvian}|%%\addlanguage{latvian}|' $pkgdir/usr/share/texmf/tex/generic/config/language.def
+   ## sed -i 's|^latvian|%%latvian|' $pkgdir/usr/share/texmf/tex/generic/config/language.dat
+
+   cd source
    ## prevent compiling Xdvi with libXp
-   sed -i~ 's|-lXp -Xext|-lXext|' texk/xdvik/configure
+   sed -i~ 's|-lXp ||' texk/xdvik/configure
    test ! -d Work && mkdir Work
    cd Work
-   echo "--> Here we go with configure..."
+   echo "--> Initial configuration..."
    ../configure --prefix=/usr \
-	--datarootdir=$pkgdir/usr/share \
-   	--datadir=$pkgdir/usr/share \
-	--disable-multiplatform --without-dialog \
-        --without-psutils --without-texinfo --without-t1utils \
-	--with-system-zlib --with-system-pnglib \
-	--with-system-ncurses --with-system-t1lib \
-	--with-system-gd --with-fontconfig=/usr/lib \
-	--with-system-freetype2 --with-freetype2-libdir=/usr/lib \
-	--with-freetype2-include=/usr/include/freetype2 \
-	--with-xdvi-x-toolkit=xaw --with-cxx-runtime-hack \
-        --without-omega --without-aleph --without-graphite || return 1
-   ### fixes for xindy 
-   find utils/xindy -name Makefile -exec sed -i -e "s|^prefix =.\+$|prefix = $pkgdir/usr|" '{}' \; || return 1
-   ### we skip that, coz it requires an almost full texlive installation for compilation of the documentation:
-   sed -i -e "s|^MAKE_RULES = make-rules|MAKE_RULES = ''|" -e "s|^DOCS = doc|DOCS = ''|" utils/xindy/Makefile || return 1
+    --datarootdir=$pkgdir/usr/share \
+    --datadir=$pkgdir/usr/share \
+    --mandir=$pkgdir/usr/share/man \
+    --disable-native-texlive-build \
+    --with-tex-banner="TeX Live 2009/Arch Linux" \
+    --disable-multiplatform --disable-dialog \
+    --disable-psutils --disable-t1utils --disable-xz \
+    --with-system-zlib --with-system-pnglib --with-system-ncurses \
+    --with-system-t1lib --with-system-gd --with-system-xpdf \
+    --with-system-freetype2 --with-freetype2-libdir=/usr/lib \
+    --with-freetype2-include=/usr/include/freetype2 \
+    --with-xdvi-x-toolkit=xaw --disable-dump-share  \
+    --disable-aleph --without-graphite \
+    --enable-xindy || return 1
+   #############################################################
    #############################################################
    echo "-------------------------------------------------------"
-   echo "--> ... and now we build the whole beast"
+   echo "--> Building the whole beast ..."
    make || return 1
    #############################################################
+
+   ### fixes for xindy
+   find utils/xindy -name Makefile -exec sed -i -e "s|^prefix =.\+$|prefix = $pkgname/usr|" -e "s|^mandir =.\+$|mandir = \${prefix}/share/man|" -e "s|^datadir =.\+$|datadir = \${datarootdir}/texmf|" -e "s|^docdir =.\+$|docdir = \${datadir}/doc/xindy|" '{}' \; || return 1
    echo "-------------------------------------------------------"
-   echo "--> ... proceeding with make install"
+   echo "--> Proceeding with make install ..."
    install -d -m755 $pkgdir/usr/share/man/man5
-   make prefix=$pkgdir/usr texmf=$startdir/pkg/usr/share/texmf install || return 1
+   make prefix=$pkgdir/usr texmf=$pkgdir/usr/share/texmf install || return 1
    echo "-------------------------------------------------------"
-   echo "--> ...fixing wrong symlinks to scripts under /usr/bin/"
+   echo "--> Fixing symlinks for scripts ..."
    for f in $pkgdir/usr/bin/* ; do
 	   if [ -L $f ]; then
 		   target=`ls -l "$f" | sed 's/^.\+ -> //'`
 		   if [[ "$target" == ..* ]]; then
-			   newtarget=`echo $target | sed -e 's|../|/usr/share/|'`
+			   newtarget=`echo $target | sed -e 's#../#/usr/share/#'`
 			   rm -f $f
 			   ln -s $newtarget $f
-			   test -f $pkgdir/$newtarget && chmod a+x $startdir/pkg/$newtarget
+			   test -f $pkgdir/$newtarget && chmod a+x $pkgdir/$newtarget
 		   fi
 	   fi
    done
+
+   ## create symlinks for formats 
+   echo "--> Create symlinks for TeX formats ..."
+   $pkgdir/usr/bin/texlinks -f $pkgdir/usr/share/texmf/web2c/fmtutil.cnf $pkgdir/usr/bin/ || return 1
+   #############################################################
    
- #############################################################
- ## CLEAN UP... 
-   echo "Cleaning up"
+   ## CLEAN UP... 
+   echo "--> ...Cleaning up installation"
    # remove tlmgr from PATH
    rm -f $pkgdir/usr/bin/tlmgr
+   # spurious symlink
+   rm -f $pkgdir/usr/bin/man
+   
+   # the mandirs contain Makefiles ...
+   find $pkgdir -name Makefile -delete
 
-   for d in $pkgdir/usr/texmf/scripts/*; do
-	   dname=`basename $d`
-	   test ! -d $pkgdir/usr/share/texmf/scripts/$dname && mv $d $startdir/pkg/usr/share/texmf/scripts/
-   done
+   rm -f $pkgdir/usr/share/texmf/scripts/texlive/*-{win32,w32}*
+   rm -rf $pkgdir/usr/share/texmf/scripts/tlgs
+   rm -rf $pkgdir/usr/share/texmf/asymptote
+
+   # make install targets are somewhat chaotic :)
+   mv -n  $pkgdir/usr/texmf/* $pkgdir/usr/share/texmf/
+   mv -n  $pkgdir/usr/texmf-dist/* $pkgdir/usr/share/texmf/
    rm -rf $pkgdir/usr/{texmf,texmf-dist}
+   rmdir  $pkgdir/usr/share/lcdf-typetools
+
    # most man files went to two different places:
    for i in 1 5; do
 	   # remove pdf versions of manpages:
-	   rm -f $pkgdir/usr/share/texmf/man/man$i/*.pdf
-	   for f in $pkgdir/usr/share/texmf/doc/man/man$i/*; do
-		   bf=`basename $f`
-		   if [[ ! -f $pkgdir/usr/share/man/man$i/$bf ]]; then
-			   mv -f $f $pkgdir/usr/share/man/man$i/
-		   fi
-	   done
+     rm -f $pkgdir/usr/share/texmf/doc/man/man$i/*.pdf
+     # move to 
+     mv -n $pkgdir/usr/share/texmf/doc/man/man$i/*.$i $pkgdir/usr/share/man/man$i/
    done
-   # remove extra documentation:
-   rm -rf $pkgdir/usr/share/texmf/doc/
+   # remove all doc (essentially xindy and duplicated man files)
+   rm -rf $pkgdir/usr/share/texmf/doc
    # those files are also in base, but "make install" duplicated them here:
    rm -rf $pkgdir/usr/share/texmf/bibtex/
-   #TODO leave info files ?
-   rm -rf $pkgdir/usr/share/{info,doc}
-   # remove files that belong to texinfo
-   for f in info infokey install-info makeinfo texi2dvi pdftexi2dvi texi2pdf texindex; do
+   # remove files that belong to asymptote
+   rm -rf $pkgdir/usr/share/texmf/tex/latex/asymptote
+   for f in asy xasy; do
 	   rm -f $pkgdir/usr/share/man/man1/$f.1
-   done
-   for f in texinfo info ; do
-	   rm -f $pkgdir/usr/share/man/man5/$f.5
    done
    # remove files that belong to t1utils
    for f in t1ascii t1asm t1binary t1disasm t1mac t1unmac; do
@@ -136,14 +143,14 @@ build() {
 	   rm -f $pkgdir/usr/share/man/man1/$f.1
    done
    # remove man files that belong to omega/aleph
-   for f in omega lambda odvicopy odvips odvitype ofm2opl opl2ofm otp2ocp outocp ovf2ovp ovp2ovf oxdvi ; do
+   for f in lambda odvicopy odvitype ofm2opl opl2ofm otp2ocp outocp ovf2ovp ovp2ovf ; do
 	   rm -f $pkgdir/usr/share/man/man1/$f.1
    done
    # replace upstream texmf.cnf with ours
    rm -f $pkgdir/usr/share/texmf/web2c/texmf.cnf
    install -m644 $srcdir/texmf.cnf $pkgdir/usr/share/texmf/web2c/texmf.cnf
-   ## remove omega and aleph from fmtutil.cnf
-   sed -i -e '/omega/d' -e '/aleph/d' $pkgdir/usr/share/texmf/web2c/fmtutil.cnf || return 1
+   ## remove aleph from fmtutil.cnf
+   sed -i -e '/aleph/d' $pkgdir/usr/share/texmf/web2c/fmtutil.cnf || return 1
    ###################################################################
    # copy config files to texmf-config tree
    install -d -m755 $pkgdir/usr/share/texmf-config/web2c
@@ -173,11 +180,9 @@ build() {
    # clean updmap.cfg
    sed -i '/^\(Map\|MixedMap\)/d' $pkgdir/usr/share/texmf-config/web2c/updmap.cfg
    sed -i '/^#! \(Map\|MixedMap\)/d' $pkgdir/usr/share/texmf-config/web2c/updmap.cfg
-   # fix hard-coded paths in /usr/bin/xindy
-   sed -i "s|'/.\+/pkg/usr|'/usr|" $pkgdir/usr/bin/xindy
+   # fix hard-coded paths in xindy.pl
+   sed -i "s|'/.\+/pkg/usr|'/usr|" $pkgdir/usr/share/texmf/scripts/xindy/xindy.pl
    # move xindy modules to /usr/share/xindy
    rm -rf $pkgdir/usr/share/xindy
    mv $pkgdir/usr/share/texmf/xindy $pkgdir/usr/share/
 }
-
-
