Todo List: Remove usage of makepkg subroutines from PKGBUILDs
git-svn-id: file:///srv/repos/svn-packages/svn@373617 eb2447ed-0c53-47e4-bac8-5bc4a241df78

diff --git a/trunk/PKGBUILD b/trunk/PKGBUILD
--- a/trunk/PKGBUILD
+++ b/trunk/PKGBUILD
@@ -78,7 +78,7 @@ package() {
   for file in "$pkgdir/etc/mail/spamassassin/"*.pre; do
 	  clean_file="${file#"$pkgdir/"}"
 	  if ! in_array "$clean_file" "${backup[@]}"; then
-		  error "backup array is missing an entry for '$clean_file'"
+		  echo "ERROR: backup array is missing an entry for '$clean_file'" >&2
 		  backup_incomplete=1
 	  fi
   done
