FS#46242 Fix typos in the messages
Author:  Christoph Gysin

git-svn-id: file:///srv/repos/svn-packages/svn@249894 eb2447ed-0c53-47e4-bac8-5bc4a241df78

diff --git a/trunk/syslinux-install_update b/trunk/syslinux-install_update
--- a/trunk/syslinux-install_update
+++ b/trunk/syslinux-install_update
@@ -54,7 +54,7 @@ check_is_in() {
 get_disk() {
     local part=$1
     if [[ ! -b "${part}" ]]; then
-        echo >&2 "error: '$part' is not a valid block partition!"
+        echo >&2 "error: '$part' is not a valid block device!"
         exit 1
     fi
 
@@ -67,7 +67,7 @@ get_disk() {
             ;;
     esac
     if [[ ! -b "${disk}" ]]; then
-        echo >&2 "error: '$diskj' is not a valid block device!"
+        echo >&2 "error: '$disk' is not a valid block device!"
         exit 1
     fi
     echo $disk
