archrelease: copy trunk to testing-x86_64, testing-i686
git-svn-id: file:///srv/repos/svn-packages/svn@199887 eb2447ed-0c53-47e4-bac8-5bc4a241df78

diff --git a/repos/testing-x86_64/PKGBUILD b/repos/testing-x86_64/PKGBUILD
--- a/repos/testing-x86_64/PKGBUILD
+++ b/repos/testing-x86_64/PKGBUILD
@@ -1,10 +1,10 @@
 # Maintainer : Tobias Powalowski <tpowa@archlinux.org>
 # Maintainer : Thomas Bächler <thomas@archlinux.org>
-# Contributor: Keshav Padram (the.ridikulus.rat) (aatt) (gemmaeiil) (ddoott) (ccoomm)>
+# Contributor: Keshav Padram Amburay <(the ddoott ridikulus ddoott rat) (aatt) (gemmaeiil) (ddoott) (ccoomm)>
 
 pkgname="syslinux"
 pkgver="6.02"
-pkgrel="5"
+pkgrel="6"
 arch=('x86_64' 'i686')
 pkgdesc="Collection of boot loaders that boot from FAT, ext2/3/4 and btrfs filesystems, from CDs and via PXE"
 url="http://syslinux.zytor.com/"
@@ -30,53 +30,7 @@ md5sums=('6f275813a1b08cf852e55c0a3f8fbc78'
          '9376f18fa3e42fc36cffa4cff0a84c09'
          '9dbede6b71a4de9e46aac4aad65334d7')
 
-_build_syslinux_bios() {
-    
-    rm -rf "${srcdir}/${pkgname}-${pkgver}-bios/" || true
-    cp -r "${srcdir}/${pkgname}-${pkgver}" "${srcdir}/${pkgname}-${pkgver}-bios"
-    cd "${srcdir}/${pkgname}-${pkgver}-bios/"
-    
-    ## Do not try to build syslinux with our default LDFLAGS, it will fail
-    unset LDFLAGS
-    make PYTHON="python2" bios
-    make PYTHON="python2" bios installer 
-}
-
-_build_syslinux_efi64() {
-    
-    rm -rf "${srcdir}/${pkgname}-${pkgver}-efi64/" || true
-    cp -r "${srcdir}/${pkgname}-${pkgver}" "${srcdir}/${pkgname}-${pkgver}-efi64"
-    cd "${srcdir}/${pkgname}-${pkgver}-efi64/"
-    
-    ## Unset all compiler FLAGS for efi64 build
-    unset CFLAGS
-    unset CPPFLAGS
-    unset CXXFLAGS
-    unset LDFLAGS
-    unset MAKEFLAGS
-    
-    make PYTHON="python2" efi64
-    make PYTHON="python2" efi64 installer 
-}
-
-_build_syslinux_efi32() {
-    
-    rm -rf "${srcdir}/${pkgname}-${pkgver}-efi32/" || true
-    cp -r "${srcdir}/${pkgname}-${pkgver}" "${srcdir}/${pkgname}-${pkgver}-efi32"
-    cd "${srcdir}/${pkgname}-${pkgver}-efi32/"
-    
-    ## Unset all compiler FLAGS for efi32 build
-    unset CFLAGS
-    unset CPPFLAGS
-    unset CXXFLAGS
-    unset LDFLAGS
-    unset MAKEFLAGS
-    
-    make PYTHON="python2" efi32
-    make PYTHON="python2" efi32 installer 
-}
-
-build() {
+prepare() {
     
     cd "${srcdir}/${pkgname}-${pkgver}/"
     
@@ -95,7 +49,62 @@ build() {
     # http://bugzilla.syslinux.org/show_bug.cgi?id=31
     # http://www.syslinux.org/archives/2013-October/020971.html
     patch -Np1 -i "${srcdir}/syslinux-6.02-fix-chainloading.patch"
+    
+}
 
+_build_syslinux_bios() {
+    
+    rm -rf "${srcdir}/${pkgname}-${pkgver}-bios/" || true
+    cp -r "${srcdir}/${pkgname}-${pkgver}" "${srcdir}/${pkgname}-${pkgver}-bios"
+    cd "${srcdir}/${pkgname}-${pkgver}-bios/"
+    
+    ## Do not try to build syslinux with our default LDFLAGS, it will fail
+    unset LDFLAGS
+    make PYTHON="python2" bios
+    make PYTHON="python2" bios installer
+    
+}
+
+_build_syslinux_efi64() {
+    
+    rm -rf "${srcdir}/${pkgname}-${pkgver}-efi64/" || true
+    cp -r "${srcdir}/${pkgname}-${pkgver}" "${srcdir}/${pkgname}-${pkgver}-efi64"
+    cd "${srcdir}/${pkgname}-${pkgver}-efi64/"
+    
+    ## Unset all compiler FLAGS for efi64 build
+    unset CFLAGS
+    unset CPPFLAGS
+    unset CXXFLAGS
+    unset LDFLAGS
+    unset MAKEFLAGS
+    
+    make PYTHON="python2" efi64
+    make PYTHON="python2" efi64 installer
+    
+}
+
+_build_syslinux_efi32() {
+    
+    rm -rf "${srcdir}/${pkgname}-${pkgver}-efi32/" || true
+    cp -r "${srcdir}/${pkgname}-${pkgver}" "${srcdir}/${pkgname}-${pkgver}-efi32"
+    cd "${srcdir}/${pkgname}-${pkgver}-efi32/"
+    
+    ## Unset all compiler FLAGS for efi32 build
+    unset CFLAGS
+    unset CPPFLAGS
+    unset CXXFLAGS
+    unset LDFLAGS
+    unset MAKEFLAGS
+    
+    make PYTHON="python2" efi32
+    make PYTHON="python2" efi32 installer
+    
+}
+
+build() {
+    
+    cd "${srcdir}/${pkgname}-${pkgver}/"
+    
     ## Build syslinux-efi
     if [[ "${CARCH}" == "x86_64" ]]; then
         _build_syslinux_efi64
@@ -145,7 +154,7 @@ _package_syslinux_bios() {
     
 }
 
-package() {
+_package_syslinux_efi() {
     
     cd "${srcdir}/${pkgname}-${pkgver}/"
     
@@ -158,6 +167,14 @@ package() {
         cd "${srcdir}/${pkgname}-${pkgver}-efi32/"
         make INSTALLROOT="${pkgdir}/" AUXDIR="/usr/lib/syslinux/" efi32 install
     fi
+    
+}
+
+package() {
+    
+    cd "${srcdir}/${pkgname}-${pkgver}/"
+    
+    _package_syslinux_efi
     
     _package_syslinux_bios
     
