upgpkg: spamassassin 3.4.2-3
Add missing files to backup array

git-svn-id: file:///srv/repos/svn-packages/svn@352342 eb2447ed-0c53-47e4-bac8-5bc4a241df78

diff --git a/spamassassin/trunk/PKGBUILD b/spamassassin/trunk/PKGBUILD
--- a/spamassassin/trunk/PKGBUILD
+++ b/spamassassin/trunk/PKGBUILD
@@ -3,7 +3,7 @@
 # Contributor: Manolis Tzanidakis
 pkgname=spamassassin
 pkgver=3.4.2
-pkgrel=2
+pkgrel=3
 pkgdesc="A mail filter to identify spam."
 arch=('x86_64')
 license=('APACHE')
@@ -20,7 +20,10 @@ backup=('etc/mail/spamassassin/local.cf'
         'etc/mail/spamassassin/v310.pre'
         'etc/mail/spamassassin/v312.pre'
         'etc/mail/spamassassin/v320.pre'
-        'etc/mail/spamassassin/v330.pre')
+        'etc/mail/spamassassin/v330.pre'
+        'etc/mail/spamassassin/v340.pre'
+        'etc/mail/spamassassin/v341.pre'
+		'etc/mail/spamassassin/v342.pre')
 install="${pkgname}.install"
 source=("https://www.us.apache.org/dist/${pkgname}/source/Mail-SpamAssassin-${pkgver}.tar.gz"{,.asc}
         'spamassassin.tmpfiles.d'
@@ -68,4 +71,16 @@ package() {
 	  install -Dm644 /dev/stdin "$pkgdir/usr/lib/sysusers.d/$pkgname.conf"
 
   install -Dm644 "$srcdir/spamassassin.tmpfiles.d" "$pkgdir/usr/lib/tmpfiles.d/$pkgname.conf"
+
+  backup_incomplete=0
+  for file in "$pkgdir/etc/mail/spamassassin/"*.pre; do
+	  clean_file="${file#"$pkgdir/"}"
+	  if ! in_array "$clean_file" "${backup[@]}"; then
+		  error "backup array is missing an entry for '$clean_file'"
+		  backup_incomplete=1
+	  fi
+  done
+  if ((backup_incomplete)); then
+	  exit 1
+  fi
 }
