db-move: moved syslinux from [testing] to [core] (i686, x86_64)
git-svn-id: file:///srv/repos/svn-packages/svn@234998 eb2447ed-0c53-47e4-bac8-5bc4a241df78

diff --git a/syslinux/repos/core-x86_64/syslinux-install_update b/syslinux/repos/core-x86_64/syslinux-install_update
--- a/syslinux/repos/core-x86_64/syslinux-install_update
+++ b/syslinux/repos/core-x86_64/syslinux-install_update
@@ -239,13 +239,18 @@ set_active() {
         esac
 
         if [[ "$ptb" = MBR ]]; then
-            if sfdisk "$disk" -A "$partnum" &>/dev/null; then
+            if sfdisk "$disk" --activate "$partnum" &>/dev/null; then
                 echo "Boot Flag Set - $part"
             else
                 echo "FAILED to Set the boot flag on $part"
                 exit 3
             fi
         elif [[ "$ptb" = GPT ]]; then
+            if [[ ! -e /usr/bin/sgdisk ]]; then
+                echo "FAILED to set attribute Legacy BIOS Bootable. sgdisk is not found - please install 'gptfdisk' package."
+                exit 3
+            fi
+
             if sgdisk "$disk" --attributes="$partnum":set:2 &>/dev/null; then
                 echo "Attribute Legacy Bios Bootable Set - $part"
             else
