upgpkg: opera 9.61-1
git-svn-id: file:///srv/repos/svn-packages/svn@16857 eb2447ed-0c53-47e4-bac8-5bc4a241df78

diff --git a/opera/trunk/opera-qt4-theme.patch b/opera/trunk/opera-qt4-theme.patch
--- a/opera/trunk/opera-qt4-theme.patch
+++ b/opera/trunk/opera-qt4-theme.patch
@@ -1,16 +1,11 @@
---- opera.orig	2008-05-29 15:30:05.436910051 -0300
-+++ opera	2008-05-29 15:30:29.337109130 -0300
+--- opera.orig	2008-10-22 19:37:21.000000000 +0200
++++ opera	2008-10-22 19:38:13.000000000 +0200
 @@ -30,7 +30,7 @@
-  done
-    test -z "$toset" || die Missing parameter for $arg
-    
-    -test "${_QTSTYLE_FROM_CMDLINE_}" = 'NO' && test -f "$HOME/.qt/qtrc" &&  
-    _OPERA_QTSTYLE=`sed -n 's/^style=//p' $HOME/.qt/qtrc` && test  
-    "$_OPERA_QTSTYLE" && set -- "$@" -style "$_OPERA_QTSTYLE"
-    +test "${_QTSTYLE_FROM_CMDLINE_}" = 'NO' && test -f  
-    "$HOME/.config/Trolltech.conf" && _OPERA_QTSTYLE=`sed -n 's/^style=//p'  
-    $HOME/.config/Trolltech.conf` && test "$_OPERA_QTSTYLE" && set -- "$@"  
-    -style "$_OPERA_QTSTYLE"
-    
-    
-      # Add ending path divider "/" if missing, so execution won't fail
+ done
+ test -z "$toset" || die Missing parameter for $arg
+ 
+-test "${_QTSTYLE_FROM_CMDLINE_}" = 'NO' && test -f "$HOME/.qt/qtrc" && _OPERA_QTSTYLE=`sed -n 's/^style=//p' $HOME/.qt/qtrc` && test "$_OPERA_QTSTYLE" && set -- "$@" -style "$_OPERA_QTSTYLE"
++test "${_QTSTYLE_FROM_CMDLINE_}" = 'NO' && test -f "$HOME/.config/Trolltech.conf" && _OPERA_QTSTYLE=`sed -n 's/^style=//p' $HOME/.config/Trolltech.conf` && test "$_OPERA_QTSTYLE" && set -- "$@" -style "$_OPERA_QTSTYLE"
+ 
+ 
+ # Add ending path divider "/" if missing, so execution won't fail
