archrelease: copy trunk to extra-x86_64
git-svn-id: file:///srv/repos/svn-packages/svn@374374 eb2447ed-0c53-47e4-bac8-5bc4a241df78

diff --git a/repos/extra-x86_64/PKGBUILD b/repos/extra-x86_64/PKGBUILD
--- a/repos/extra-x86_64/PKGBUILD
+++ b/repos/extra-x86_64/PKGBUILD
@@ -2,7 +2,7 @@
 # Contributor: Dale Blount <dale@archlinux.org>
 # Contributor: Manolis Tzanidakis
 pkgname=spamassassin
-pkgver=3.4.3
+pkgver=3.4.4
 pkgrel=1
 pkgdesc="A mail filter to identify spam."
 arch=('x86_64')
@@ -31,7 +31,7 @@ source=("https://ftp.fau.de/apache/${pkgname}/source/Mail-SpamAssassin-${pkgver}
         'spamassassin.tmpfiles.d'
         'spamassassin.service')
 validpgpkeys=(D8099BC79E17D7E49BC21E31FDE52F40F7D39814)
-sha512sums=('d2fd657d3c20273b0c06cb1da083d757d3f2a7f60c7ed6e6ad8f98e6df33c9c5f3824f0531abf5dbc32b0dde22979d7d671231fa2ef0d8b073ea6804c5de0c3a'
+sha512sums=('b6efa1c733ddf810b189ec69445faeae6488ee2671f87f56b49ec3bf85690bf7950aa5ce251c1f1371b2bbe4fb88dbce0a162c9a24a48ed5e6584f9019611552'
             'SKIP'
             '994ebb2b6c127521676f35879017112a33da53ad99431837d06973a9abfc4aa0434ea2c9b19073ff2cc877ebe3a5a7fe8525bc93222fd05956069ce73e5ae389'
             '5ad6aa8d992375b0989413d36ff0485f792ac9211a47e6a2a7fa5c0b9eb353aa6efe6f55da3ff4480bdef24beb4fa456c64c5a5ce72e8ad6c93c171c969fd6ee')
@@ -78,7 +78,7 @@ package() {
   for file in "$pkgdir/etc/mail/spamassassin/"*.pre; do
 	  clean_file="${file#"$pkgdir/"}"
 	  if ! in_array "$clean_file" "${backup[@]}"; then
-		  error "backup array is missing an entry for '$clean_file'"
+		  echo "ERROR: backup array is missing an entry for '$clean_file'" >&2
 		  backup_incomplete=1
 	  fi
   done
