upgpkg: libotf 0.9.16-3: Better freetype patch that keeps some variables needed elsewhere
git-svn-id: file:///srv/repos/svn-packages/svn@382459 eb2447ed-0c53-47e4-bac8-5bc4a241df78

diff --git a/libotf/trunk/replace-freetype-config.patch b/libotf/trunk/replace-freetype-config.patch
--- a/libotf/trunk/replace-freetype-config.patch
+++ b/libotf/trunk/replace-freetype-config.patch
@@ -1,46 +1,33 @@
-From: Hilko Bengen <bengen@debian.org>
-Date: Sat, 27 Oct 2018 00:53:35 +0200
-Subject: Use pkg-config for freetype
-
----
- configure.ac | 29 ++++++++---------------------
- 1 file changed, 8 insertions(+), 21 deletions(-)
-
---- a/configure.ac
-+++ b/configure.ac
-@@ -48,27 +48,14 @@
+--- libotf-0.9.16/configure.ac
++++ libotf-0.9.16/configure.ac
+@@ -48,23 +48,24 @@
  AC_FUNC_ALLOCA
  AC_FUNC_MALLOC
  
--# Check for Freetype2 usability.
++PKG_PROG_PKG_CONFIG
++
+ # Check for Freetype2 usability.
 -AC_CHECK_PROG(HAVE_FREETYPE_CONFIG, freetype-config, yes)
 -if test "x$HAVE_FREETYPE_CONFIG" = "xyes"; then
 -  FREETYPE_INC=`freetype-config --cflags`
--  CPPFLAGS="$CPPFLAGS $FREETYPE_INC"
--  AC_CHECK_HEADER(ft2build.h, HAVE_FREETYPE=yes,
--  			      HAVE_FREETYPE=no CPPFLAGS=$save_CPPFLAGS)
--  if test "x$HAVE_FREETYPE" = "xyes" ; then
++PKG_CHECK_MODULES(FREETYPE, freetype2, [
++  FREETYPE_INC="$FREETYPE_CFLAGS"
+   CPPFLAGS="$CPPFLAGS $FREETYPE_INC"
+   AC_CHECK_HEADER(ft2build.h, HAVE_FREETYPE=yes,
+   			      HAVE_FREETYPE=no CPPFLAGS=$save_CPPFLAGS)
+   if test "x$HAVE_FREETYPE" = "xyes" ; then
 -    FREETYPE_LD_FLAGS=`freetype-config --libs`;
--    LIBS="$LIBS $FREETYPE_LD_FLAGS"
--    AC_CHECK_LIB(freetype, FT_Init_FreeType, HAVE_FREETYPE=yes,
--    			   		     HAVE_FREETYPE=no)
--  fi
++    FREETYPE_LD_FLAGS="$FREETYPE_LIBS"
+     LIBS="$LIBS $FREETYPE_LD_FLAGS"
+     AC_CHECK_LIB(freetype, FT_Init_FreeType, HAVE_FREETYPE=yes,
+     			   		     HAVE_FREETYPE=no)
+   fi
 -fi
--
--if test "x$HAVE_FREETYPE" != "xyes" ; then
--  echo "Freetype library wan't found in your system!"
--  exit 1
--fi
--AC_SUBST(FREETYPE_INC)
--AC_SUBST(FREETYPE_LD_FLAGS)
-+PKG_CHECK_MODULES(
-+        [FREETYPE],
-+        [freetype2],
-+        [
-+                CFLAGS="$CFLAGS $FREETYPE_CFLAGS"
-+                LIBS="$LIBS $FREETYPE_LIBS"
-+        ],
-+        [AC_MSG_ERROR([Can't find Freetype library])])
++])
  
- if test "x$no_x" != "xyes"; then
-   X11_XT_XAW_XMU="-lX11 -lXt -lXaw -lXmu"
+ if test "x$HAVE_FREETYPE" != "xyes" ; then
+-  echo "Freetype library wan't found in your system!"
++  echo "Freetype library not found in your system!"
+   exit 1
+ fi
+ AC_SUBST(FREETYPE_INC)
