archrelease: copy trunk to extra-x86_64
git-svn-id: file:///srv/repos/svn-packages/svn@136014 eb2447ed-0c53-47e4-bac8-5bc4a241df78

diff --git a/fam/repos/extra-x86_64/fam b/fam/repos/extra-x86_64/fam
--- a/fam/repos/extra-x86_64/fam
+++ b/fam/repos/extra-x86_64/fam
@@ -6,13 +6,10 @@
 PID=`pidof -o %PPID /usr/sbin/famd`
 case "$1" in
   start)
-    #Check for running portmap, start when not running
-    ck_daemon rpcbind && /etc/rc.d/rpcbind start
     stat_busy "Starting File Alteration Monitor"
     if ck_daemon rpcbind; then
-      stat_fail
-      echo "ERROR: rpcbind is not running"
-      exit 1
+      echo "ERROR: Refusing to start fam without rpcbind running!" >&2
+      stat_die
     fi
     if [ -z "$PID" ]; then
        /usr/sbin/famd -T 0 -c /etc/fam/fam.conf
