upgpkg: coreutils 6.12-1
git-svn-id: file:///srv/repos/svn-packages/svn@2936 eb2447ed-0c53-47e4-bac8-5bc4a241df78

diff --git a/coreutils/trunk/coreutils-i18n.patch b/coreutils/trunk/coreutils-i18n.patch
--- a/coreutils/trunk/coreutils-i18n.patch
+++ b/coreutils/trunk/coreutils-i18n.patch
@@ -1,9 +1,9 @@
 --- /dev/null	2007-03-01 09:16:39.219409909 +0000
-+++ coreutils-6.8+/tests/sort/sort-mb-tests	2007-03-01 15:08:24.000000000 +0000
++++ coreutils-6.8+/tests/misc/sort-mb-tests	2007-03-01 15:08:24.000000000 +0000
 @@ -0,0 +1,58 @@
 +#! /bin/sh
 +case $# in
-+  0) xx='../../src/sort';;
++  0) xx='../src/sort';;
 +  *) xx="$1";;
 +esac
 +test "$VERBOSE" && echo=echo || echo=:
@@ -16,38 +16,38 @@
 +locale -k LC_CTYPE 2>&1 | grep -q charmap.*UTF-8 || exit 77
 +errors=0
 +
-+$xx -t ＠ -k2 -n mb1.I > mb1.O
++$xx -t ＠ -k2 -n misc/mb1.I > misc/mb1.O
 +code=$?
 +if test $code != 0; then
 +  $echo "Test mb1 failed: $xx return code $code differs from expected value 0" 1>&2
 +  errors=`expr $errors + 1`
 +else
-+  cmp mb1.O $srcdir/mb1.X > /dev/null 2>&1
++  cmp misc/mb1.O $srcdir/misc/mb1.X > /dev/null 2>&1
 +  case $? in
 +    0) if test "$VERBOSE"; then $echo "passed mb1"; fi;;
-+    1) $echo "Test mb1 failed: files mb1.O and $srcdir/mb1.X differ" 1>&2
-+       (diff -c mb1.O $srcdir/mb1.X) 2> /dev/null
++    1) $echo "Test mb1 failed: files misc/mb1.O and $srcdir/misc/mb1.X differ" 1>&2
++       (diff -c misc/mb1.O $srcdir/misc/mb1.X) 2> /dev/null
 +       errors=`expr $errors + 1`;;
 +    2) $echo "Test mb1 may have failed." 1>&2
-+       $echo The command "cmp mb1.O $srcdir/mb1.X" failed. 1>&2
++       $echo The command "cmp misc/mb1.O $srcdir/misc/mb1.X" failed. 1>&2
 +       errors=`expr $errors + 1`;;
 +  esac
 +fi
 +
-+$xx -t ＠ -k4 -n mb2.I > mb2.O
++$xx -t ＠ -k4 -n misc/mb2.I > misc/mb2.O
 +code=$?
 +if test $code != 0; then
 +  $echo "Test mb2 failed: $xx return code $code differs from expected value 0" 1>&2
 +  errors=`expr $errors + 1`
 +else
-+  cmp mb2.O $srcdir/mb2.X > /dev/null 2>&1
++  cmp misc/mb2.O $srcdir/misc/mb2.X > /dev/null 2>&1
 +  case $? in
 +    0) if test "$VERBOSE"; then $echo "passed mb2"; fi;;
-+    1) $echo "Test mb2 failed: files mb2.O and $srcdir/mb2.X differ" 1>&2
-+       (diff -c mb2.O $srcdir/mb2.X) 2> /dev/null
++    1) $echo "Test mb2 failed: files misc/mb2.O and $srcdir/misc/mb2.X differ" 1>&2
++       (diff -c misc/mb2.O $srcdir/misc/mb2.X) 2> /dev/null
 +       errors=`expr $errors + 1`;;
 +    2) $echo "Test mb2 may have failed." 1>&2
-+       $echo The command "cmp mb2.O $srcdir/mb2.X" failed. 1>&2
++       $echo The command "cmp misc/mb2.O $srcdir/misc/mb2.X" failed. 1>&2
 +       errors=`expr $errors + 1`;;
 +  esac
 +fi
@@ -60,53 +60,55 @@
 +test $errors = 0 || errors=1
 +exit $errors
 --- /dev/null	2007-03-01 09:16:39.219409909 +0000
-+++ coreutils-6.8+/tests/sort/mb2.I	2007-03-01 15:08:24.000000000 +0000
++++ coreutils-6.8+/tests/misc/mb2.I	2007-03-01 15:08:24.000000000 +0000
 @@ -0,0 +1,4 @@
 +Apple＠ＡＡ10＠＠20
 +Banana＠ＡＡ5＠＠30
 +Citrus＠ＡＡ20＠＠5
 +Cherry＠ＡＡ30＠＠10
 --- /dev/null	2007-03-01 09:16:39.219409909 +0000
-+++ coreutils-6.8+/tests/sort/mb2.X	2007-03-01 15:08:24.000000000 +0000
++++ coreutils-6.8+/tests/misc/mb2.X	2007-03-01 15:08:24.000000000 +0000
 @@ -0,0 +1,4 @@
 +Citrus＠ＡＡ20＠＠5
 +Cherry＠ＡＡ30＠＠10
 +Apple＠ＡＡ10＠＠20
 +Banana＠ＡＡ5＠＠30
 --- /dev/null	2007-03-01 09:16:39.219409909 +0000
-+++ coreutils-6.8+/tests/sort/mb1.I	2007-03-01 15:08:24.000000000 +0000
++++ coreutils-6.8+/tests/misc/mb1.I	2007-03-01 15:08:24.000000000 +0000
 @@ -0,0 +1,4 @@
 +Apple＠10
 +Banana＠5
 +Citrus＠20
 +Cherry＠30
 --- /dev/null	2007-03-01 09:16:39.219409909 +0000
-+++ coreutils-6.8+/tests/sort/mb1.X	2007-03-01 15:08:24.000000000 +0000
++++ coreutils-6.8+/tests/misc/mb1.X	2007-03-01 15:08:24.000000000 +0000
 @@ -0,0 +1,4 @@
 +Banana＠5
 +Apple＠10
 +Citrus＠20
 +Cherry＠30
---- coreutils-6.8+/tests/sort/Makefile.am.i18n	2007-01-24 07:47:37.000000000 +0000
-+++ coreutils-6.8+/tests/sort/Makefile.am	2007-03-01 15:09:59.000000000 +0000
-@@ -66,12 +66,14 @@
- bigfield.O bigfield.E obs-inval.O obs-inval.E realloc-buf.O realloc-buf.E
- ##test-files-end
+diff -urN coreutils-6.12-orig/tests/Makefile.am coreutils-6.12/tests/Makefile.am
+--- coreutils-6.12-orig/tests/Makefile.am	2008-05-27 13:47:53.000000000 +0200
++++ coreutils-6.12/tests/Makefile.am	2008-06-02 10:06:03.000000000 +0200
+@@ -191,6 +191,7 @@
+   misc/shuf					\
+   misc/sort					\
+   misc/sort-compress				\
++  misc/sort-mb-tests				\
+   misc/sort-merge				\
+   misc/sort-rand				\
+   misc/split-a					\
+@@ -391,6 +392,10 @@
+   $(root_tests)
  
--EXTRA_DIST = Test.pm $x-tests $(explicit) $(maint_gen)
--noinst_SCRIPTS = $x-tests
-+run_gen += mb1.0 mb2.0
-+
-+EXTRA_DIST = Test.pm $x-tests $(explicit) $(maint_gen) mb1.I mb1.X mb2.I mb2.X
-+noinst_SCRIPTS = $x-tests # $x-mb-tests
- 
- editpl = sed -e 's,@''PERL''@,$(PERL),g' -e 's,@''srcdir''@,$(srcdir),g'
- 
--TESTS = $x-tests
-+TESTS = $x-tests $x-mb-tests
- 
- mk_script = $(srcdir)/../mk-script
- $(srcdir)/$x-tests: $(mk_script) Test.pm Makefile.am
+ pr_data =					\
++  misc/mb1.X			\
++  misc/mb1.I			\
++  misc/mb2.X			\
++  misc/mb2.I			\
+   pr/0F						\
+   pr/0FF					\
+   pr/0FFnt					\
 --- coreutils-6.8+/lib/linebuffer.h.i18n	2005-05-14 07:44:24.000000000 +0100
 +++ coreutils-6.8+/lib/linebuffer.h	2007-03-01 15:08:24.000000000 +0000
 @@ -22,6 +22,11 @@
