Prepare for mkinitcpio 0.6
git-svn-id: file:///srv/repos/svn-packages/svn@67245 eb2447ed-0c53-47e4-bac8-5bc4a241df78

diff --git a/cryptsetup/trunk/encrypt_hook b/cryptsetup/trunk/encrypt_hook
--- a/cryptsetup/trunk/encrypt_hook
+++ b/cryptsetup/trunk/encrypt_hook
@@ -5,16 +5,17 @@ run_hook ()
 {
     /sbin/modprobe -a -q dm-crypt >/dev/null 2>&1
     if [ -e "/sys/class/misc/device-mapper" ]; then
-        if [ ! -c "/dev/mapper/control" ]; then
-            read dev_t < /sys/class/misc/device-mapper/dev
-            /bin/mknod "/dev/mapper/control" c $(/bin/replace "${dev_t}" ':')
+        if [ ! -e "/dev/mapper/control" ]; then
+            /bin/mknod "/dev/mapper/control" c $(cat /sys/class/misc/device-mapper/dev | sed 's|:| |')
         fi
         [ "${quiet}" = "y" ] && CSQUIET=">/dev/null"
 
         # Get keyfile if specified
         ckeyfile="/crypto_keyfile.bin"
         if [ "x${cryptkey}" != "x" ]; then
-            set -- $(/bin/replace "${cryptkey}" ':'); ckdev=$1; ckarg1=$2; ckarg2=$3
+            ckdev="$(echo "${cryptkey}" | cut -d: -f1)"
+            ckarg1="$(echo "${cryptkey}" | cut -d: -f2)"
+            ckarg2="$(echo "${cryptkey}" | cut -d: -f3)"
             if poll_device "${ckdev}" ${rootdelay}; then
                 case ${ckarg1} in
                     *[!0-9]*)
@@ -37,7 +38,8 @@ run_hook ()
 
         if [ -n "${cryptdevice}" ]; then
             DEPRECATED_CRYPT=0
-            set -- $(/bin/replace "${cryptdevice}" ':'); cryptdev="$1"; cryptname="$2";
+            cryptdev="$(echo "${cryptdevice}" | cut -d: -f1)"
+            cryptname="$(echo "${cryptdevice}" | cut -d: -f2)"
         else
             DEPRECATED_CRYPT=1
             cryptdev="${root}"
@@ -50,12 +52,12 @@ run_hook ()
         }
 
         if  poll_device "${cryptdev}" ${rootdelay}; then
-            if /bin/cryptsetup isLuks ${cryptdev} >/dev/null 2>&1; then
+            if /sbin/cryptsetup isLuks ${cryptdev} >/dev/null 2>&1; then
                 [ ${DEPRECATED_CRYPT} -eq 1 ] && warn_deprecated
                 dopassphrase=1
                 # If keyfile exists, try to use that
                 if [ -f ${ckeyfile} ]; then
-                    if eval /bin/cryptsetup --key-file ${ckeyfile} luksOpen ${cryptdev} ${cryptname} ${CSQUIET}; then
+                    if eval /sbin/cryptsetup --key-file ${ckeyfile} luksOpen ${cryptdev} ${cryptname} ${CSQUIET}; then
                         dopassphrase=0
                     else
                         echo "Invalid keyfile. Reverting to passphrase."
@@ -67,7 +69,7 @@ run_hook ()
                     echo "A password is required to access the ${cryptname} volume:"
 
                     #loop until we get a real password
-                    while ! eval /bin/cryptsetup luksOpen ${cryptdev} ${cryptname} ${CSQUIET}; do
+                    while ! eval /sbin/cryptsetup luksOpen ${cryptdev} ${cryptname} ${CSQUIET}; do
                         sleep 2;
                     done
                 fi
@@ -79,33 +81,33 @@ run_hook ()
                     err "Password succeeded, but ${cryptname} creation failed, aborting..."
                     exit 1
                 fi
-            elif [ "x${crypto}" != "x" ]; then
+            elif [ -n "${crypto}" ]; then
                 [ ${DEPRECATED_CRYPT} -eq 1 ] && warn_deprecated
-                do_oldcrypto ()
-                {
-                    if [ $# -ne 5 ]; then
-                        err "Verify parameter format: crypto=hash:cipher:keysize:offset:skip"
-                        err "Non-LUKS decryption not attempted..."
-                        return 1
-                    fi
-                    exe="/bin/cryptsetup create ${cryptname} ${cryptdev}"
-                    [ "x$(eval echo ${1})" != "x" ] && exe="${exe} --hash \"$(eval echo ${1})\""
-                    [ "x$(eval echo ${2})" != "x" ] && exe="${exe} --cipher \"$(eval echo ${2})\""
-                    [ "x$(eval echo ${3})" != "x" ] && exe="${exe} --key-size \"$(eval echo ${3})\""
-                    [ "x$(eval echo ${4})" != "x" ] && exe="${exe} --offset \"$(eval echo ${4})\""
-                    [ "x$(eval echo ${5})" != "x" ] && exe="${exe} --skip \"$(eval echo ${5})\""
-                    if [ -f ${ckeyfile} ]; then
-                        exe="${exe} --key-file ${ckeyfile}"
-                    else
-                        exe="${exe} --verify-passphrase"
-                        echo ""
-                        echo "A password is required to access the ${cryptname} volume:"
-                    fi
-                    eval "${exe} ${CSQUIET}"
-                }
-
                 msg "Non-LUKS encrypted device found..."
-                do_oldcrypto $(/bin/replace -q "${crypto}" ':')
+                if [ $# -ne 5 ]; then
+                    err "Verify parameter format: crypto=hash:cipher:keysize:offset:skip"
+                    err "Non-LUKS decryption not attempted..."
+                    return 1
+                fi
+                exe="/sbin/cryptsetup create ${cryptname} ${cryptdev}"
+                tmp=$(echo "${crypto}" | cut -d: -f1)
+                [ -n "${tmp}" ] && exe="${exe} --hash \"${tmp}\""
+                tmp=$(echo "${crypto}" | cut -d: -f2)
+                [ -n "${tmp}" ] && exe="${exe} --cipher \"${tmp}\""
+                tmp=$(echo "${crypto}" | cut -d: -f3)
+                [ -n "${tmp}" ] && exe="${exe} --key-size \"${tmp}\""
+                tmp=$(echo "${crypto}" | cut -d: -f4)
+                [ -n "${tmp}" ] && exe="${exe} --offset \"${tmp}\""
+                tmp=$(echo "${crypto}" | cut -d: -f5)
+                [ -n "${tmp}" ] && exe="${exe} --skip \"${tmp}\""
+                if [ -f ${ckeyfile} ]; then
+                    exe="${exe} --key-file ${ckeyfile}"
+                else
+                    exe="${exe} --verify-passphrase"
+                    echo ""
+                    echo "A password is required to access the ${cryptname} volume:"
+                fi
+                eval "${exe} ${CSQUIET}"
 
                 if [ $? -ne 0 ]; then
                     err "Non-LUKS device decryption failed. verify format: "
@@ -124,6 +126,6 @@ run_hook ()
                 err "Failed to open encryption mapping: The device ${cryptdev} is not a LUKS volume and the crypto= paramater was not specified."
             fi
         fi
-        nuke ${ckeyfile}
+        rm -f ${ckeyfile}
     fi
 }
