archrelease: copy trunk to testing-i686, testing-x86_64
git-svn-id: file:///srv/repos/svn-packages/svn@171897 eb2447ed-0c53-47e4-bac8-5bc4a241df78

diff --git a/systemd/repos/testing-x86_64/systemd.install b/systemd/repos/testing-x86_64/systemd.install
--- a/systemd/repos/testing-x86_64/systemd.install
+++ b/systemd/repos/testing-x86_64/systemd.install
@@ -4,12 +4,20 @@ sd_booted() {
   [ -e sys/fs/cgroup/systemd ]
 }
 
+add_privs() {
+  if ! setcap "$2" "$1" 2>/dev/null; then
+    echo "==> Warning: setcap failed, falling back to setuid root on /$1"
+    chmod u+s "$1"
+  fi
+}
+
 post_common() {
   systemd-machine-id-setup
 
-  udevadm hwdb --update
+  add_privs usr/bin/systemd-detect-virt 'cap_dac_override,cap_sys_ptrace+ep'
 
-  setcap cap_dac_override,cap_sys_ptrace+ep usr/bin/systemd-detect-virt
+  udevadm hwdb --update
+  journalctl --update-catalog
 
   if sd_booted; then
     systemctl --system daemon-reexec
