archrelease: copy trunk to extra-i686, extra-x86_64
git-svn-id: file:///srv/repos/svn-packages/svn@140768 eb2447ed-0c53-47e4-bac8-5bc4a241df78

diff --git a/repos/extra-i686/PKGBUILD b/repos/extra-i686/PKGBUILD
--- a/repos/extra-i686/PKGBUILD
+++ b/repos/extra-i686/PKGBUILD
@@ -6,55 +6,53 @@
 pkgbase=vim
 pkgname=('vim' 'gvim' 'vim-runtime')
 _topver=7.3
-_patchlevel=322
+_patchlevel=338
+__hgrev=f530aef0d959
+_versiondir="vim${_topver//./}"
 pkgver=${_topver}.${_patchlevel}
-__hgrev=5e84f6567623
 pkgrel=1
 arch=('i686' 'x86_64')
 license=('custom:vim')
 url="http://www.vim.org"
-makedepends=('gawk' 'gpm' 'python2' 'python' 'ruby' 'libxt' 'desktop-file-utils' 'gtk2'
-             'mercurial' 'rsync')
-source=(pythoncomplete.vim::http://www.vim.org/scripts/download_script.php\?src_id=10872
+makedepends=('gpm' 'python2' 'python' 'ruby' 'libxt' 'desktop-file-utils' 'gtk2')
+source=(ftp://ftp.archlinux.org/other/vim/${pkgname}-${pkgver}.tar.xz
+        pythoncomplete.vim::http://www.vim.org/scripts/download_script.php\?src_id=10872
         vimrc archlinux.vim gvim.desktop)
-md5sums=('6e7adfbd5d26c1d161030ec203a7f243'
+md5sums=('fc83d6580fd8441793fccfd26487aadb'
+         '6e7adfbd5d26c1d161030ec203a7f243'
          'e57777374891063b9ca48a1fe392ac05'
          '10353a61aadc3f276692d0e17db1478e'
          'd90413bd21f400313a785bb4010120cd')
 
-__hgroot='http://vim.googlecode.com/hg/'
-__hgrepo='vim'
-__hgbranch='default'
+# source PKGBUILD && mksource
+mksource() {
 
-_versiondir="vim${_topver//./}"
+  [[ -x /usr/bin/hg ]] || (echo "hg not found. Install mercurial." && return 1)
 
-##### Build #####
+  __hgroot='http://vim.googlecode.com/hg/'
+  __hgrepo='vim'
+  __hgbranch='default'
+
+  hg clone -b ${__hgbranch} -u ${__hgrev} "${__hgroot}${__hgrepo}" ${__hgrepo}
+
+  pushd ${__hgrepo}
+  if (( $(hg id -n) < $(hg id -nr ${__hgbranch}) )); then
+    printf 'You are not building the latest revision!\n'
+    printf "Consider updating __hgrev to $(hg id -r ${__hgbranch}).\n"
+  fi
+  popd
+
+  mv vim ${pkgname}-${pkgver}
+  find ${pkgname}-${pkgver} -depth -type d -name .hg -exec rm -rf {} \;
+  rm ${pkgname}-${pkgver}/{.hgignore,.hgtags}
+  tar -cJf ${pkgname}-${pkgver}.tar.xz ${pkgname}-${pkgver}/*
+  rm -r ${pkgname}-${pkgver}
+}
 
 build() {
   cd "${srcdir}"
 
-  msg2 'Checking out source from Mercurial...'
-
-  if [[ -d ${__hgrepo} ]]; then
-    cd ${__hgrepo}
-    hg pull -b ${__hgbranch}|| warning 'hg pull failed!'
-    hg update -r ${__hgrev}
-  else
-    hg clone -b ${__hgbranch} -u ${__hgrev} "${__hgroot}${__hgrepo}" ${__hgrepo}
-    cd ${__hgrepo}
-  fi
-
-  if (( $(hg id -n) < $(hg id -nr ${__hgbranch}) )); then
-    warning 'You are not building the latest revision!'
-    warning "Consider updating __hgrev to $(hg id -r ${__hgbranch})."
-    sleep 10
-  fi
-
-  cd ..
-  rm -rf vim-build gvim-build
-  rsync -a --exclude='.hg/' ${__hgrepo}/ vim-build
-
-  msg2 'Patching...'
+  cp -a ${pkgname}-${pkgver} vim-build
 
   # define the place for the global (g)vimrc file (set to /etc/vimrc)
   sed -i 's|^.*\(#define SYS_.*VIMRC_FILE.*"\) .*$|\1|' \
@@ -65,8 +63,6 @@ build() {
   sed -i -e 's|vi_cv_path_python, python|vi_cv_path_python, python2|' \
     vim-build/src/configure.in
   (cd vim-build/src && autoconf)
-
-  msg2 'Building...'
 
   cp -a vim-build gvim-build
 
@@ -93,8 +89,6 @@ build() {
   make
 }
 
-##### Packaging #####
-
 package_vim() {
   pkgdesc='Vi Improved, a highly configurable, improved version of the vi text editor'
   depends=("vim-runtime=${pkgver}-${pkgrel}" 'gpm')
@@ -118,7 +112,7 @@ package_vim() {
   rm -r "${pkgdir}"/usr/share/vim
 
   # license
-  install -Dm644 "${srcdir}"/vim/runtime/doc/uganda.txt \
+  install -Dm644 "${srcdir}"/vim-${pkgver}/runtime/doc/uganda.txt \
     "${pkgdir}"/usr/share/licenses/${pkgname}/license.txt
 }
 
@@ -152,7 +146,7 @@ package_gvim() {
   install -Dm644 runtime/vim48x48.png "${pkgdir}"/usr/share/pixmaps/gvim.png
 
   # license
-   install -Dm644 "${srcdir}"/vim/runtime/doc/uganda.txt \
+   install -Dm644 "${srcdir}"/vim-${pkgver}/runtime/doc/uganda.txt \
     "${pkgdir}"/usr/share/licenses/${pkgname}/license.txt
 }
 
@@ -189,7 +183,7 @@ package_vim-runtime() {
     "${pkgdir}"/usr/share/vim/vimfiles/archlinux.vim
 
   # rgb.txt file
-  install -Dm644 "${srcdir}"/vim/runtime/rgb.txt \
+  install -Dm644 "${srcdir}"/vim-${pkgver}/runtime/rgb.txt \
     "${pkgdir}"/usr/share/vim/${_versiondir}/rgb.txt
 
   # license
