archrelease: copy trunk to extra-i686, extra-x86_64
git-svn-id: file:///srv/repos/svn-packages/svn@140830 eb2447ed-0c53-47e4-bac8-5bc4a241df78

diff --git a/blender/repos/extra-i686/PKGBUILD b/blender/repos/extra-i686/PKGBUILD
--- a/blender/repos/extra-i686/PKGBUILD
+++ b/blender/repos/extra-i686/PKGBUILD
@@ -12,8 +12,8 @@
 _svn=false
 
 pkgname=blender
-pkgver=2.59
-pkgrel=3
+pkgver=2.60
+pkgrel=1
 epoch=2
 pkgdesc="A fully integrated 3D graphics creation suite"
 arch=('i686' 'x86_64')
@@ -21,12 +21,12 @@ license=('GPL')
 url="http://www.blender.org"
 depends=('libpng' 'libtiff' 'openexr' 'python' 'desktop-file-utils' \
          'shared-mime-info' 'hicolor-icon-theme' 'xdg-utils' 'glew' \
-         'freetype2' 'openal' 'libsamplerate' 'ffmpeg')
-makedepends=('cmake') # 'subversion'
+         'freetype2' 'openal' 'libsndfile' 'ffmpeg')
+makedepends=('cmake')
 install=blender.install
 if [ $_svn = false ]; then
   source=(http://download.blender.org/source/$pkgname-$pkgver.tar.gz)
-  md5sums=('6f68fe3c3c2b6a85f1ba9ebc5b1155fe')
+  md5sums=('2951df9d5f004c5e0375b53969205a38')
 else
   source=(ftp://ftp.archlinux.org/other/${pkgname}/$pkgname-$pkgver.tar.xz)
   md5sums=('7579d1139d0d6025df8afcfca64a65c4')
@@ -34,6 +34,7 @@ fi
 
 # source PKGBUILD && mksource
 mksource() {
+  [[ -x /usr/bin/svn ]] || (echo "svn not found. Install subversion." && return 1)
   _svnver=38016
   _svntrunk="https://svn.blender.org/svnroot/bf-blender/trunk/blender"
   _svnmod="$pkgname-$pkgver"
