db-move: moved rsync from [testing] to [extra] (x86_64)
git-svn-id: file:///srv/repos/svn-packages/svn@373529 eb2447ed-0c53-47e4-bac8-5bc4a241df78

diff --git a/rsync/repos/extra-x86_64/PKGBUILD b/rsync/repos/extra-x86_64/PKGBUILD
--- a/rsync/repos/extra-x86_64/PKGBUILD
+++ b/rsync/repos/extra-x86_64/PKGBUILD
@@ -1,12 +1,12 @@
 
 pkgname=rsync
 pkgver=3.1.3
-pkgrel=2
+pkgrel=3
 pkgdesc="A file transfer program to keep remote files in sync"
 arch=('x86_64')
 url="https://rsync.samba.org/"
 license=('GPL3')
-depends=('perl' 'popt' 'acl')
+depends=('acl' 'perl' 'popt' 'zlib')
 backup=('etc/rsyncd.conf' 'etc/xinetd.d/rsync')
 install=rsync.install
 validpgpkeys=('0048C8B026D4C96F0E589C2F6C859FB14B96A8C5') # Wayne Davison <wayned@users.sourceforge.net>
@@ -27,27 +27,34 @@ sha256sums=('55cc554efec5fdaad70de921cd5a5eeb6c29a95524c715f3bbf849235b0800c0'
 build() {
 	cd "$srcdir/$pkgname-$pkgver"
 
-	# rsync requires the bundled zlib to support old-style --compress
-	# This is to be reevaluated once rsync 3.1.1 is more available in the wild...
-	./configure --prefix=/usr \
+	./configure \
+		--prefix=/usr \
 		--with-included-popt=no \
-		--with-included-zlib=yes \
+		--with-included-zlib=no \
 		--disable-debug
 	make
 }
 
 check() {
 	cd "$srcdir/$pkgname-$pkgver"
+
+	# rsync fails with xattr on btrfs...
+	if [ "$(stat --file-system --printf=%T .)" = "btrfs" ]; then
+		echo "Test is known to fail on btrfs..." >&2
+		exit 1
+	fi
+
 	make test
 }
 
 package() {
 	cd "$srcdir/$pkgname-$pkgver"
+
 	make DESTDIR="$pkgdir" install
-	install -Dm644 ../rsyncd.conf "$pkgdir/etc/rsyncd.conf"
-	install -Dm644 ../rsync.xinetd "$pkgdir/etc/xinetd.d/rsync"
-	install -Dm644 ../rsyncd.service "$pkgdir/usr/lib/systemd/system/rsyncd.service"
-	install -m644 ../rsyncd.socket "$pkgdir/usr/lib/systemd/system/rsyncd.socket"
-	install -m644 ../rsyncd@.service "$pkgdir/usr/lib/systemd/system/rsyncd@.service"
-	install -Dm755 support/rrsync "$pkgdir/usr/lib/rsync/rrsync"
+	install -Dm0644 ../rsyncd.conf "$pkgdir/etc/rsyncd.conf"
+	install -Dm0644 ../rsync.xinetd "$pkgdir/etc/xinetd.d/rsync"
+	install -Dm0644 ../rsyncd.service "$pkgdir/usr/lib/systemd/system/rsyncd.service"
+	install -m0644 ../rsyncd.socket "$pkgdir/usr/lib/systemd/system/rsyncd.socket"
+	install -m0644 ../rsyncd@.service "$pkgdir/usr/lib/systemd/system/rsyncd@.service"
+	install -Dm0755 support/rrsync "$pkgdir/usr/lib/rsync/rrsync"
 }
